### ISSUE TITLE
ALZ-PowerShell-Module support for windows_arm64

### ISSUE THREAD

**Issue by zebak007** [Azure/ALZ-PowerShell-Module#121]
### Description
Following summer heat, my Intel laptop got really too hot and started to stop during my team sessions. So I just ordered a new copilot-PC with SnapDragon and so far experience has been amazing except I just got stuck with the following error on ALZ/Accelerator PowerShell Module. 

Any chance to get the ALZ powershell support for windows_arm64 ?

PS C:\git\ALZ-BootStrap> Deploy-Accelerator -i "terraform" -b "alz_azuredevops" -inputs "c:\\git\\ALZ-BootStrap\\config\\experimental01.yaml" -Output ".\\ALZ-Exp01"  
Getting ready to deploy the accelerator with you...
 
Checking you have the latest version of Terraform installed...
 
Checking and Downloading the bootstrap module...
The directory for .\\ALZ-Exp01\bootstrap\v2.2.0 has been created and populated.
 
Checking and Downloading the starter module...
The directory for .\\ALZ-Exp01\starter\v2.2.0 has been created and populated.
Write-Error: C:\Users\cbezenco\Documents\PowerShell\Modules\ALZ\2.2.0\Private\Tools\Get-HCLParserTool.ps1:12:27
Line |
  12 |          $osArchitecture = Get-OSArchitecture
     |                            ~~~~~~~~~~~~~~~~~~
     | Unsupported OS and architecture combination: windows_arm64
       
### Describe the solution you'd like

ALZ-PowerShell-Module support for windows_arm64

**Comment by jaredfholgate** [comment]
A fix to support amd64 compatibility mode was released. We have also spoken the the maintainers of Terraform Core and HCLtoJSON and they will be pushing arm64 binaries soon, so we'll revisit this and support the native binaries in the future.
