### ISSUE TITLE
Bug report: Pipeline error in GitHub

### ISSUE THREAD

**Issue by richardf5** [Azure/ALZ-PowerShell-Module#135]
### Expected Behavior

GitHub Action should be able to run successfully. 

### Current Behavior

Error: Error parsing called workflow. <org><prefix>-shared-templates/.github/workflows/cd-template.yaml@main: workflow was not found.

Both repositories exist. 

![image](https://github.com/user-attachments/assets/5b02bdc9-5d53-49cb-8e16-1c8635b22295)

### Steps to Reproduce

Note: Error occurs regardless of using typed inputs or steering YAML file.

1.  New Terraform Accelerator using Deploy-Accelerator (ALZ version 3.0.1)
2. Solution deploys bootstrap successfully.
3. Attempt to run 02 CD pipeline.

My current config:

- Using Complete Starter
- starter_location: "australieast"
- Using GitHub Organisation
- use_self_hosted_runners: "false"
- use_private_networking: "false"
- use_runner_group: "false"

### Context (Environment)

* Operating System and version as reported by `$PSVersionTable.OS`:
PSVersion 7.4.4
Windows 11 23H2

* PowerShell versions as reported by `$PSVersionTable.PSEdition`:

**Comment by oZakari** [comment]
Hi @richardf5, are you actually seeing the this file in your repo as well? `shared-templates/.github/workflows/cd-template.yaml`

**Comment by richardf5** [comment]
Hi. I am.
![image](https://github.com/user-attachments/assets/167f1412-c6c7-4b56-84dc-2e802ee598aa)

**Comment by jaredfholgate** [comment]
I'm wondering if this is a GitHub org permissions issue stopping the main repo from accessing the templates repo. As a workaround, you could try setting the `use_separate_repository_for_templates` input to `false`.

It would be useful to see your GitHub org licensing level and settings for default repository access. I will attempt to replicate in a licensed org too.

**Comment by richardf5** [comment]
Hi. Apologies, I've been on different work for a couple of weeks.

I'll try to replicate the issue today. Currently have another error relating to not being allowed to register a certain resource type. Will take a look and log an issue if required.

**Comment by oZakari** [comment]
Thanks for the update @richardf5, please feel free to re-open you are able to replicate the issue again.
