### ISSUE TITLE
Question: Onboarding new Resources post ALZ deployment.

### ISSUE THREAD

**Issue by sumanbikram** [Azure/ALZ-PowerShell-Module#141]
Hello Everyone
I have a couple of question in regard to ALZ terraform with Azure Devops. I competed boot strapping and also ran CD. Number 2 pipeline that creates many resources. Now I would like to deploy resources according to my company's requirement.

Can I create terraform modules for my resources and trigger the same pipeline or its better to create separate CI/CD for my further deployment?  
Also, if I have include/drop something as a part of ALZ then do you think it's possible? If so, is there any input file that I can modify?
I can see so many resources while CICD, is there any document what exactly resources are created and would like to know about pricing so that i can create a document what exactly we will pay for. 

Thanks

**Comment by jaredfholgate** [comment]
We are working on an extension to the accelerator to encompass Application Landing Zones (and subscription vending). In the meantime, you would need to create your own repos and pipelines for the resources you want to deploy into your application subscriptions. You should not be using the ALZ pipeline to deploy anything other than the platform landing zone.

If you use the `complete` module for Terraform you can pick and choose what is deployed in the platform landing zone using the config file.

There is a balance between cost and security depending on you organisations needs. If your focus is cost, then choose Microsoft-Hosted agents and public networking. If your focus is security and less on cost, then self-hosted agents and private networking is most likely what you want to be looking at. There is a basic list of the deployed resources here: https://github.com/Azure/ALZ-PowerShell-Module/wiki#github

I'm closing this for now, but feel free to re-open if there is an issue.
