### ISSUE TITLE
Feature request: Easy method / description for overriding policy assignments.

### ISSUE THREAD

**Issue by richardf5** [Azure/ALZ-PowerShell-Module#146]
### Description

We need to be able to override some of the policy created and assigned by the Enterprise Scale module. Normally this is done by creating override files in the /lib folder I believe.

### Describe the solution you'd like

A method or code update to allow us to easily override policy parameters, assignments and effects.

In the YAML Scheme Reference, it does mention a field called 'archetypes_config_overrides' - is this where it could be done?

As an example, the 'Configure backup on virtual machines without a given tag to a new recovery services vault with a default policy' isn't deployed with the name of the tag we'd need to stop it creating Recovery Vaults everywhere!

Another example: The 'Management port access from the Internet should be blocked' policy doesn't like complex NSG rules i.e. those that have a list of ports including port ranges. Until the issue is identified, we'd like to be able to put that policy in audit mode.

**Comment by jaredfholgate** [comment]
You can use a custom lib folder by updating the code post bootstrap. For vNext we will likely provide a mechanism for this.

I'm not sure there is a way to turn on or off policy assignments using variables, so you would need a custom lib for that.

Closing this for now, since we'll provide better support in vNext and there is a workaround to add your own lib folder and update the .tf files post bootstrap.

**Comment by richardf5** [comment]
Gents. It's not clear 'how' to add a lib folder and therefore put the overrides in.
I'm aware of how to add extra Terraform code in post-bootstrap, but not how to do the work with the lib folder considering that the module is only downloaded upon each init stage.

Can you please provide guidance?

**Comment by jaredfholgate** [comment]
You need to use `library_path` variable like in this example: https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Deploy-Custom-Landing-Zone-Archetypes#maintf

It is quite possible I am missing something here?
