### ISSUE TITLE
Bug: Wiki content out of date: User Guide `apply_approvers` is an invalid data type string not array

### ISSUE THREAD

**Issue by mikejonestechno** [Azure/ALZ-PowerShell-Module#184]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Infrastrcuture as Code Type? (Required)

bicep

### Module Versions (Required)

ALZ PowerShell Module: 3.0.4
Accelerator Bootstrap Modules: x.x.x
Terraform Starter Modules: x.x.x
Bicep Starter Modules: x.x.x

### Input arguments of the ALZ-PowerShell-Module (Optional)

apply_approvers: "abc@xyz.com,def@xyz.com,ghi@xyz.com"

### Expected Behaviour (Required)

The comma separated list of approvers is valid and terraform plan is successful.

### Actual Behaviour (Required)

Terraform plan for apply failed with exit code 1
```
Error: Invalid value for input variable
   on override.tfvars.json line 14:
   14:   "apply_approvers": "abc@xyz.com,def@xyz.com,ghi@xyz.com"
The given value is not suitable for var.apply_approvers declared at variables.input.tf:84,1-27: list of string required.
```

### Steps to Reproduce (Optional)

Wiki page [[User Guide] Quick Start Phase 2 Azure DevOps](https://github.com/Azure/ALZ-PowerShell-Module/wiki/%5BUser-Guide%5D-Quick-Start-Phase-2-Azure-DevOps) 

Item 4. says copy the content from the (WIKI PAGE CACHED FILE) [inputs-azure-devops-bicep-complete.yaml](https://github.com/Azure/ALZ-PowerShell-Module/wiki/examples/powershell-inputs/inputs-azure-devops-bicep-complete.yaml)
that contains:
```
apply_approvers: "<email-address-list>"
```

Also the wiki page table in item 5. describes `apply_approvers` as `<email-address-list>` with an example
> This is a comma-separated list like `abc@xyz.com,def@xyz.com,ghi@xyz.com` ... Use empty string "" to disable approvals.

This 'wiki' content is misleading and implies a string data type. The actual value should be an array of strings enclosed in square brackets as found in the actual [inputs-azure-devops-complete.yaml file](https://raw.githubusercontent.com/Azure/ALZ-PowerShell-Module/aa0f60ef6887f2d81713fe94c0c752e92a87b636/docs/wiki/examples/powershell-inputs/inputs-azure-devops-bicep-complete.yaml):
```
apply_approvers: ["<email-address>"]
```

Please update the docs for both AzureDevOps and GitHub quickstart with the correct example and re-generate and re-publish the wiki page content.
> This is an array of emails like `["abc@xyz.com","def@xyz.com","ghi@xyz.com"]` ... Use empty array [] to disable approvals.

**Comment by oZakari** [comment]
Re-synced the wiki and no longer getting sent to the outdated cached page.
