### ISSUE TITLE
Bug: CD pipeline failing on "Custom Management Group Diagnostic Settings" step due to mission permission for User-Assigned Managed Identity

### ISSUE THREAD

**Issue by cspring86** [Azure/ALZ-PowerShell-Module#188]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Infrastrcuture as Code Type? (Required)

bicep

### Module Versions (Required)

ALZ PowerShell Module: 3.0.4
Accelerator Bootstrap Modules: 3.1.2
Terraform Starter Modules: N/A
Bicep Starter Modules: 0.19.2

### Expected Behaviour (Required)

The "02 Azure Landing Zones Continuous Delivery" pipeline should have successfully performed a "Deploy" for the "Custom Management Group Diagnostic Settings" step.

### Actual Behaviour (Required)

The "02 Azure Landing Zones Continuous Delivery" pipeline kept looping when performing a "Deploy" for the "Custom Management Group Diagnostic Settings" step.

Manually Formatted Output:
```
15:12:38 - Error: Code=InvalidTemplateDeployment; Message=Deployment failed with multiple errors: 
'Authorization failed for template resource 'toLa' of type 'Microsoft.Insights/diagnosticSettings'. The client 'xxx' with object id 'xxx' does not have permission to perform action 'Microsoft.Insights/diagnosticSettings/write' at scope '/providers/Microsoft.Management/managementGroups/alz-platform-management/providers/Microsoft.Insights/diagnosticSettings/toLa'.
:Authorization failed for template resource 'toLa' of type 'Microsoft.Insights/diagnosticSettings'. The client 'xxx' with object id 'xxx' does not have permission to perform action 'Microsoft.Insights/diagnosticSettings/write' at scope '/providers/Microsoft.Management/managementGroups/alz-decommissioned/providers/Microsoft.Insights/diagnosticSettings/toLa'.
:Authorization failed for template resource 'toLa' of type 'Microsoft.Insights/diagnosticSettings'. The client 'xxx' with object id 'xxx' does not have permission to perform action 'Microsoft.Insights/diagnosticSettings/write' at scope '/providers/Microsoft.Management/managementGroups/alz/providers/Microsoft.Insights/diagnosticSettings/toLa'.
:Authorization failed for template resource 'toLa' of type 'Microsoft.Insights/diagnosticSettings'. The client 'xxx' with object id 'xxx' does not have permission to perform action 'Microsoft.Insights/diagnosticSettings/write' at scope '/providers/Microsoft.Management/managementGroups/alz-landingzones/providers/Microsoft.Insights/diagnosticSettings/toLa'.
:Authorization failed for template resource 'toLa' of type 'Microsoft.Insights/diagnosticSettings'. The client 'xxx' with object id 'xxx' does not have permission to perform action 'Microsoft.Insights/diagnosticSettings/write' at scope '/providers/Microsoft.Management/managementGroups/alz-platform/providers/Microsoft.Insights/diagnosticSettings/toLa'.
:Authorization failed for template resource 'toLa' of type 'Microsoft.Insights/diagnosticSettings'. The client 'xxx' with object id 'xxx' does not have permission to perform action 'Microsoft.Insights/diagnosticSettings/write' at scope '/providers/Microsoft.Management/managementGroups/alz-sandbox/providers/Microsoft.Insights/diagnosticSettings/toLa'.
:Authorization failed for template resource 'toLa' of type 'Microsoft.Insights/diagnosticSettings'. The client 'xxx' with object id 'xxx' does not have permission to perform action 'Microsoft.Insights/diagnosticSettings/write' at scope '/providers/Microsoft.Management/managementGroups/alz-landingzones-corp/providers/Microsoft.Insights/diagnosticSettings/toLa'.
:Authorization failed for template resource 'toLa' of type 'Microsoft.Insights/diagnosticSettings'. The client 'xxx' with object id 'xxx' does not have permission to perform action 'Microsoft.Insights/diagnosticSettings/write' at scope '/providers/Microsoft.Management/managementGroups/alz-landingzones-online/providers/Microsoft.Insights/diagnosticSettings/toLa'.
:Authorization failed for template resource 'toLa' of type 'Microsoft.Insights/diagnosticSettings'. The client 'xxx' with object id 'xxx' does not have permission to perform action 'Microsoft.Insights/diagnosticSettings/write' at scope '/providers/Microsoft.Management/managementGroups/alz-platform-connectivity/providers/Microsoft.Insights/diagnosticSettings/toLa'.
:Authorization failed for template resource 'toLa' of type 'Microsoft.Insights/diagnosticSettings'. The client 'xxx' with object id 'xxx' does not have permission to perform action 'Microsoft.Insights/diagnosticSettings/write' at scope '/providers/Microsoft.Management/managementGroups/alz-platform-identity/providers/Microsoft.Insights/diagnosticSettings/toLa'.'

```

It looks like the "id-alz-mgmt-eastus2-apply-001" User-Assigned Managed Identity doesn't have the "Microsoft.Insights/diagnosticSettings/write" permission.

### Important Factoids (Optional)

This is the first CD pipeline run using the new accelerator.

The Azure resources had been deployed previously using the "classic" accelerator.

**Comment by oZakari** [comment]
Hi @cspring86, sometimes these permissions take some time to fully propagate. I have seen instances of them taking 30-45 minutes. Can you please re-run the deployment, and let me know if you're still running into the error?

**Comment by cspring86** [comment]
@oZakari I'm still getting the same error. It looks like the "id-alz-mgmt-eastus2-apply-001" User-Assigned Managed Identity needs additional permissions.

**Comment by oZakari** [comment]
I haven't been able to replicate this one after doing multiple deployments over the top of an existing deployment. I have also not heard of others with this permissions issue. Any particular parameters you adjusted, or did you happen to make any changes to the diagnostic module directly? Also, if you add the permission, does the deployment complete or does it error with other missing permissions?

**Comment by cspring86** [comment]
> I haven't been able to replicate this one after doing multiple deployments over the top of an existing deployment. I have also not heard of others with this permissions issue. Any particular parameters you adjusted, or did you happen to make any changes to the diagnostic module directly? Also, if you add the permission, does the deployment complete or does it error with other missing permissions?

Interesting.

Doing a bit of searching, I have found that the [ALZ-Bicep](https://github.com/Azure/ALZ-Bicep) is creating the relevant diagnostic settings that are causing the error: https://github.com/Azure/ALZ-Bicep/blob/main/infra-as-code/bicep/modules/mgDiagSettings/mgDiagSettings.bicep#L18. The `parDiagnosticSettingsName` property is "toLa", which can be seen in the error messages.

I've also searched the [accelerator-bootstrap-modules](https://github.com/Azure/accelerator-bootstrap-modules) repository and can see that the "Azure Landing Zones Management Group What If (alz-mgmt)" custom role *is* granted the `Microsoft.Insights/diagnosticSettings/write` permission ([here](https://github.com/Azure/accelerator-bootstrap-modules/blob/main/alz/azuredevops/variables.hidden.tf#L251)), but the "Azure Landing Zones Management Group Contributor (alz-mgmt)" custom role is *not* ([here](https://github.com/Azure/accelerator-bootstrap-modules/blob/main/alz/azuredevops/variables.hidden.tf#L213)).

I think that this is the issue and also explains why the CI (What If) part of the pipeline passes, but the CD part doesn't.

I'd, naively, possibly, expect that the Contributor role would have the *same* base permissions as the Reader role and then additional "write" permissions on top of these. However, I can see that the `Microsoft.Insights/diagnosticSettings/write` permission isn't the only one that not also in the Contributor role.

**Comment by cspring86** [comment]
Ok, so I've manually granted the "Azure Landing Zones Management Group Contributor (alz-mgmt)" custom role the `Microsoft.Insights/diagnosticSettings/write` permission and that step passes now.

However, it is now failing on the "Built-in and Custom Policy Assignments Deployment" step.

The error is this:
```
Error: Code=InvalidTemplateDeployment; Message=Deployment failed with multiple errors: 'Authorization failed for template resource 'Deploy-MDEndpoints' of type 'Microsoft.Authorization/policyAssignments'. The client 'xxx' with object id 'xxx' does not have permission to perform action 'Microsoft.Authorization/policyAssignments/write' at scope '/providers/Microsoft.Management/managementGroups/alz/providers/Microsoft.Authorization/policyAssignments/Deploy-MDEndpoints'.:Authorization failed for template resource 'Deploy-MDFC-Config-H224' of type 'Microsoft.Authorization/policyAssignments'. The client 'xxx' with object id 'xxx' does not have permission to perform action 'Microsoft.Authorization/policyAssignments/write' at scope '/providers/Microsoft.Management/managementGroups/alz/providers/Microsoft.Authorization/policyAssignments/Deploy-MDFC-Config-H224'.'
```

Funnily enough, this is another one of the permissions granted to the "Azure Landing Zones Management Group What If (alz-mgmt)" custom role and not the "Azure Landing Zones Management Group Contributor (alz-mgmt)" custom role.

I think it makes sense to grant all permissions that the Reader role has to the Contributor role as the baseline.

**Comment by cspring86** [comment]
Adding these 2 permissions from the Reader role to the Contributor role gets the CD pipeline working:

```
Microsoft.Insights/diagnosticSettings/write
Microsoft.Authorization/policyAssignments/write
```

It might be also worth adding some timeouts to the pipelines, even if they're oversized because these errors don't appear to cause the step to fail, it just keeps re-trying. I didn't wait to see if it ever did fail though, so it may fail eventually on its own.

**Comment by oZakari** [comment]
Thanks for the detailed information @cspring86. Some of the inconsistencies are due to how the what-if operator works. However,  I have created a PR to add both of these permissions.

**Comment by cspring86** [comment]
Amazing, thanks @oZakari !
