### ISSUE TITLE
Bug: Issue with upgrading files with the Deploy-Accelerator -replacefiles parameter.

### ISSUE THREAD

**Issue by jantorep** [Azure/ALZ-PowerShell-Module#189]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Infrastrcuture as Code Type? (Required)

bicep

### Module Versions (Required)

ALZ PowerShell Module: 7.4.5
Accelerator Bootstrap Modules: 3.0.4
Terraform Starter Modules: x.x.x
Bicep Starter Modules: 3.0.4

### Input arguments of the ALZ-PowerShell-Module (Optional)

Deploy-Accelerator -i "bicep" -b "alz_github" -o "C:\GitRepo\reponame\" -bicepLegacyMode $true -replaceFiles $True

### Debug Output/Panic Output (Optional)

```shell
Configuration directory C:\GitRepo\HemitHF\reponame\config already exists and the replacefiles parameter is set to False. Will skil overwriting the config directory.
```

### Expected Behaviour (Required)

With this it should update the files that has changed under config folder. Even if i remove the config folder or just keep everything empty the same behaviour is shown.

### Actual Behaviour (Required)

Does not replace files under \config

### Steps to Reproduce (Optional)

run the command.

**Comment by jaredfholgate** [comment]
The `replaceFiles` option is only for local development purposes. It only works in combination with the `bootstrapModuleOverrideFolderPath` and or `starterModuleOverrideFolderPath`. 

Closing this for now as we no longer support the `bicepLegacyMode` option as of v4. 

There is a different solution for upgrading to newer versions, which it does by default when a new version is available or specified. https://github.com/Azure/ALZ-PowerShell-Module/wiki/Upgrade-Guide
