### ISSUE TITLE
feat: perform templating as part of the bootstrap, outside the module

### ISSUE THREAD

**Issue by kewalaka** [Azure/ALZ-PowerShell-Module#239]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Infrastructure as Code Type? (Required)

terraform

### Starter Module? (Required)

terraform - basic

### Use Case (Required)

Using yaml or templates (via terraform's template functionality) would provide more flexibility for inputs and make them easier to maintain.

### Proposed Solution (Required)

Presently the inputs support yaml or json documents, and some hard coded templating is done within the module (e..g for the various starter locations).

I think a better way would be to allow templated yaml/json input files, combined with a tfvars, which the PS module calls.  This would allow for arbitrary templated variables and potentially remove the need to do this within the starter module locals.

This could use the templating capability in terraform, thus wouldn't require any additional libraries.

It would make it easier to standardise common 'snippets' like naming components.

### References (Optional)

I've got some samples that I use for vending, happy to illustrate if helpful.

**Comment by jaredfholgate** [comment]
I’m not following this 100%. If this is specifically for the `basic` starter module, then the intention is to replace that with an example config file for `complete_multi_region`. This starter module already supports templating.
