### ISSUE TITLE
Bug: ALZ module not installing

### ISSUE THREAD

**Issue by ashley-kainos** [Azure/ALZ-PowerShell-Module#247]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Infrastructure as Code Type? (Required)

not relevant

### PowerShell Module Version (Optional)

latest

### Starter Module? (Required)

other

### Input arguments of the ALZ-PowerShell-Module (Optional)

I'm trying to install the ALZ module to be able to deploy teh accelerator and getting the following:    

![Image](https://github.com/user-attachments/assets/4b840e04-4efd-45cc-9019-3fe02bfa3c13)

### Debug Output/Panic Output (Optional)

```shell

```

### Expected Behaviour (Required)

when I run get-installmodule after install-module I shoudl see module install and version

### Actual Behaviour (Required)

see screen shot above

**Comment by jtracey93** [comment]
Hey @ashley-kainos,

Looks like you are using PowerShell v5 there and not the newer [v7](https://learn.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-windows?view=powershell-7.4)

Try installing it in `v7` as thats where its supported only.
