### ISSUE TITLE
ALZBicepAccelerator-Create message to use different subscription ids for connectivity, identity, and management inputs

### ISSUE THREAD

**Issue by oZakari** [Azure/ALZ-PowerShell-Module#41]
### Description
To align to ALZ best practices, we want to avoid having customers create connectivity, management, and identity resources within the same subscription. 

### Describe the solution you'd like
When the module requests the user inputs for the subscription IDs for connectivity, management, and identity, and provide message to let them know that it is best practice to not utilize a single subscription.

### Additional context

Dont's allow this or any variation where the same subscription IDs are referenced more than once..
![image](https://user-images.githubusercontent.com/30884663/229929128-9a64d8eb-49be-466b-9dc2-7d1ceae0bfdb.png)

**Comment by baartch** [comment]
Shouldn't it be considered to allow variations of the Enterprise-Scale?

Deploying something like _Trey Research_, where I have only one Subscription for Platform, would not be possible anymore.
https://github.com/Azure/Enterprise-Scale/blob/main/docs/reference/treyresearch/README.md

To deploy _Trey Research_, I entered three times the single Subscription I had and later changed it in the `config\custom-parameters\subPlacementAll.parameters.all.json` file:
```json
{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentParameters.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "parTopLevelManagementGroupPrefix": {
      "value": "comp"
    },
    "parTopLevelManagementGroupSuffix": {
      "value": ""
    },
    "parIntRootMgSubs": {
      "value": []
    },
    "parPlatformMgSubs": {
      "value": ["00000000-1111-2222-3333-444444444444"] /* my Platform subscription */
    },
    "parPlatformManagementMgSubs": {
      "value": [] /* empty */
    },
    "parPlatformConnectivityMgSubs": {
      "value": [] /* empty */
    },
    "parPlatformIdentityMgSubs": {
      "value": [] /* empty */
    },
```

**Comment by jtracey93** [comment]
Hey @baartch,

Good ask, ive created a feature request for you here #78 for the single platform sub ask.

**Comment by oZakari** [comment]
Closing as feature request [here ](https://github.com/Azure/ALZ-PowerShell-Module/issues/78) to provide warning but still support single platform sub.
