### ISSUE TITLE
hubNetworking.parameters.all.json parameter naming issue for parHubNetworkName & parAzFirewallName

### ISSUE THREAD

**Issue by MilesCameron-DMs** [Azure/ALZ-PowerShell-Module#51]
The parameters file hubNetworking.parameters.all.json does not update the following 2 parameters to the correct location set in parLocation:

- parHubNetworkName
- parAzFirewallName

### Expected Behavior
Parameters should be set to:

alz-hub-< parLocation >
alz-azfw-< parLocation >

So for example if parLocation is 'uksouth' the parameters should be:

alz-hub-uksouth
alz-azfw-uksouth

### Current Behavior
Parameters are set as:

alz-hub-eastus
alz-azfw-eastus

### Possible Solution
Unknown

### Steps to Reproduce
Run a deployment and set the location

**Comment by oZakari** [comment]
Good catch @MilesCameron-DMs, will work on getting this updated.

**Comment by oZakari** [comment]
Fix included in [0.2.1 release](https://github.com/Azure/ALZ-PowerShell-Module/releases/tag/0.2.1)
