### ISSUE TITLE
Faulty value for LoggingResourceGroup in config-asset for v0.14.0

### ISSUE THREAD

**Issue by picccard** [Azure/ALZ-PowerShell-Module#53]
## Description

Inside the asset `v0.14.0.config.json` the resourcegroup for logging seems to be referenced with two different values.

 
https://github.com/Azure/ALZ-PowerShell-Module/blob/25171050a4da2e7a02bb64babd38d957f90ca7cd/src/ALZ/Assets/alz-bicep-config/v0.14.0.config.json#L325-L327

https://github.com/Azure/ALZ-PowerShell-Module/blob/25171050a4da2e7a02bb64babd38d957f90ca7cd/src/ALZ/Assets/alz-bicep-config/v0.14.0.config.json#L510-L512

**Comment by oZakari** [comment]
Thanks @picccard, will get this fixed today.

**Comment by oZakari** [comment]
Fix included with [0.2.2 release](https://github.com/Azure/ALZ-PowerShell-Module/releases/tag/0.2.2)
