### ISSUE TITLE
$env:PROCESSOR_ARCHITECTURE is empty in Codespaces/Dev containers

### ISSUE THREAD

**Issue by janegilring** [Azure/ALZ-PowerShell-Module#71]
In GitHub Codespaces and VS Code Development containers, $env:PROCESSOR_ARCHITECTURE is empty - leading to an error when running `New-ALZEnvironment `.

### Expected Behavior

`New-ALZEnvironment -alzIacProvider bicep -alzCicdPlatform github` should not throw an error due to $env:PROCESSOR_ARCHITECTURE being empty

### Current Behavior

```
New-ALZEnvironment -alzIacProvider bicep -alzCicdPlatform github                                                                                                               in pwsh at 10:08:54
Getting ready to create a new ALZ environment with you...
Downloading alz-terraform-accelerator Terraform module to .
InvalidOperation: /tmp/ALZ-PowerShell-Module/src/ALZ/Private/Get-HCLParserTool.ps1:23:27                                
Line |                                                                                                                  
  23 |          $architecture = $($env:PROCESSOR_ARCHITECTURE).ToLower()                                                
     |                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                           
     | You cannot call a method on a null-valued expression.                
```

### Steps to Reproduce

1. Open a GitHub Codespace or VS Code Development container
2. Open a terminal running pwsh
3. Install ALZ-PowerShell-Module
4. Run New-ALZEnvironment -alzIacProvider bicep -alzCicdPlatform github  

### Context (Environment)

* Operating System and version as reported by `$PSVersionTable.OS`: Linux 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023
* PowerShell versions as reported by `$PSVersionTable.PSEdition`: 7.3.6

**Comment by oZakari** [comment]
Hi @janegilring, thank you for calling out this issue! I will add this to our backlog to get a fix out as soon as we can.

**Comment by jaredfholgate** [comment]
@oZakari I am unsure why this method would be called if `bicep` is chosen as IaC. I will look into this and raise a PR along with #74.
