### ISSUE TITLE
bug: env PROCESSOR_ARCHITECTURE does not exist on Linux

### ISSUE THREAD

**Issue by matt-FFFFFF** [Azure/ALZ-PowerShell-Module#73]
https://github.com/Azure/ALZ-PowerShell-Module/blob/6c6953cbdeba54f670688395492b9ec10b40fa42/src/ALZ/Private/Get-HCLParserTool.ps1#L23

**Comment by matt-FFFFFF** [comment]
Maybe use `uname -i` to receive `x86_64`

**Comment by jtracey93** [comment]
#71 related

cc: @oZakari & @jaredfholgate
