### ISSUE TITLE
Allow Single Platform Subscription Option - Bicep

### ISSUE THREAD

**Issue by jtracey93** [Azure/ALZ-PowerShell-Module#78]
### Description

See https://github.com/Azure/ALZ-PowerShell-Module/issues/41#issuecomment-1759230726 for more info

### Describe the solution you'd like

Create option to specify a single platform subscriptions to achieve the Trey Research architecture.

Perhaps make it similar to the ALZ Portal experience where it warns you that 3 are best, but if warning is acknowledge then allow single sub for platform.

Once acknowledged it should configure the parameter files to achieve the single platform sub architecture

One area I see some work required would be the policy assignments in Bicep to meet the single platform sub solution.

**Comment by jaredfholgate** [comment]
@jtracey93 Is this still something we want to support?
