### ISSUE TITLE
Get-ALZGithubRelease.ps1 doesn't retrieve all releases from Github

### ISSUE THREAD

**Issue by MarkFarkas** [Azure/ALZ-PowerShell-Module#85]
### Expected Behavior
The function should be able to donwload any release of ALZ-Bicep

### Current Behavior
The function can only find 30 releases. Since this list returned by Github is not consistent, releases are not found randomly. In my case It's unable to donwload the latest release, v0.16.5

### Possible Solution
Implement pagination

### Steps to Reproduce
Get-ALZGithubRelease -githubRepoUrl 'https://github.com/Azure/ALZ-Bicep' -releases $('v0.16.5')
WARNING: Release v0.16.5 was not found on GitHub Repo: Azure/ALZ-Bicep

### Context (Environment)
I was trying to download the latest release of ALZ-Bicep using New-ALZEnvironment
* Operating System and version as reported by `$PSVersionTable.OS`: Microsoft Windows 10.0.19045
* PowerShell versions as reported by `$PSVersionTable.PSEdition`: Core

Get-ALZGithubRelease.ps1 doesn't retrieve all releases from Github

### Detailed Description
The function Get-ALZGithubRelease.ps1 will only retrieve 30 releases from Github, as per https://docs.github.com/en/free-pro-team@latest/rest/releases/releases?apiVersion=2022-11-28#list-releases:~:text=per_page%20integer,Default%3A%2030

Since there are currently 44 releases for the ALZ-Bicep only a portion of them can be found by the function.

**Comment by jtracey93** [comment]
Hey @MarkFarkas,

Can you confirm the version of the ALZ PowerShell module you have installed?

```pwsh
get-module -name ALZ -ListAvailable
```

The latest is `v0.2.20` and you can install that with `Update-Module -Name 'ALZ'`

There also looked to be an oddity on the GitHub side with `v0.16.5` which I think I have just resolved so please try again and you should be all good 👍 

Let us know

Thanks

**Comment by MarkFarkas** [comment]
Hello @jtracey93 , I am using version v0.2.20. I have confirmed that this in indeed an issue with the module and already made a PR: https://github.com/Azure/ALZ-PowerShell-Module/pull/86

**Comment by oZakari** [comment]
Hi @markfarkas, the function was restructured yesterday to pull specific release versions instead of all of the releases available for a particular repo, so this should no longer be an issue. I will also go ahead and close your PR for now, but if you end up running into any other issues, please let us know and thank you for bringing this up!
